version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env

  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  jupyter-api:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --no-browser --notebook-dir=/django --NotebookApp.token='${JUPYTER_TOKEN}'
    volumes:
      - .:/django
      - ./jupyter_config:/root/.jupyter
    environment:
      - DJANGO_SETTINGS_MODULE=link_scraper.settings
      - DJANGO_ALLOW_ASYNC_UNSAFE="true"

volumes:
  postgres_data: